/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author up800143
 */
public class HomeGui extends javax.swing.JFrame {
    AddClass add = new AddClass(this);
    ShopGUI shop = new ShopGUI(this);
    UserGUI settings = new UserGUI(this);

    /**
     * Creates new form testClass
     */
    public HomeGui() {
        initComponents();
  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();
        invenBtn = new javax.swing.JLabel();
        shopBtn = new javax.swing.JLabel();
        settingsBtn = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setResizable(false);

        viewPanel.setBackground(new java.awt.Color(44, 62, 80));

        invenBtn.setBackground(new java.awt.Color(255, 255, 255));
        invenBtn.setText("            Inventory");
        invenBtn.setOpaque(true);
        invenBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invenBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invenBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invenBtnMouseEntered(evt);
            }
        });

        shopBtn.setBackground(new java.awt.Color(255, 255, 255));
        shopBtn.setText("           Shopping List");
        shopBtn.setOpaque(true);
        shopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shopBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shopBtnMouseEntered(evt);
            }
        });

        settingsBtn.setBackground(new java.awt.Color(255, 255, 255));
        settingsBtn.setText("           Settings");
        settingsBtn.setOpaque(true);
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });

        userName.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(settingsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shopBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGap(130, 130, 130))
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addComponent(invenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(userName)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(invenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     /**
    * Changes the color of a label 
    * 
    * @param label the label object to change color
    */
    private void hoverBtn(JLabel label){
        Color myCustomColor = new Color(231, 76, 60);
        label.setBackground(myCustomColor);
    }
    private void invenBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invenBtnMouseClicked
        add.setLocationRelativeTo(null);
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_invenBtnMouseClicked

    private void shopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopBtnMouseClicked
        shop.setLocationRelativeTo(null);
        shop.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_shopBtnMouseClicked

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        settings.setLocationRelativeTo(null);
        settings.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void invenBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invenBtnMouseEntered
        hoverBtn(invenBtn);
    }//GEN-LAST:event_invenBtnMouseEntered

    private void shopBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopBtnMouseEntered
        hoverBtn(shopBtn);
    }//GEN-LAST:event_shopBtnMouseEntered

    private void invenBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invenBtnMouseExited
         invenBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_invenBtnMouseExited

    private void shopBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopBtnMouseExited
        shopBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_shopBtnMouseExited

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseEntered
        hoverBtn(settingsBtn);
    }//GEN-LAST:event_settingsBtnMouseEntered
    
     /**
     * Return the panel
     * @return panel of the AddClass JFrame
     */
    public JPanel getPanel(){
        return viewPanel;
    }
    
    /**
     *
     * @return userName input from the User
     */
    public JLabel getUsername(){
       return userName;
    }
    
    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseExited
         settingsBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_settingsBtnMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeGui().setVisible(true);
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invenBtn;
    private javax.swing.JLabel settingsBtn;
    private javax.swing.JLabel shopBtn;
    private javax.swing.JLabel userName;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
